# Configuration constants

TEMPERATURE_ULTRA_PRECISION_STD_DEV = 3.0
TEMPERATURE_VERY_PRECISION_STD_DEV = 5.0
TEMPERATURE_ALLOWED_MEAN_DIFF = 0.5

HUMIDITY_ALLOWED_DIFF = 1.0
MONOXIDE_ALLOWED_DIFF = 3.0
